spring:
  profiles:
    active: -dev

---

spring:
  profiles: dev
  application:
    name: springcloud-config-client-dev

server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev-7001.com:7001/eureka/
---

spring:
  profiles: test
  application:
    name: springcloud-config-client-test

server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test-7001.com:7001/eureka/
